version: '3.8'

services:
  tasks-manager-backend:
    image:  tasks-manager-backend
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports: 
      - "27018:27018"
    volumes:
      - data:/data/db
